language: node_js
# enable container-based builds
# see (http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/)
sudo: false
# Cache ruby gems used by S3 deployment
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '4.0'
before_script:
- export PATH=$PWD/node_modules/.bin:$PATH
- make update-manifest-versions
after_success:
- make firefox-addon
- make publish-chrome-extension
- make publish-passcards-cli
before_deploy:
- make test-package
deploy:
- provider: s3
  access_key_id: AKIAJLAC2I2QPV6E33GA
  secret_access_key:
    secure: YyxwCqc8aPvsX432y3YhnRye2c/hyYylu6EBSGxgDG0Jg7IXtHKkcslGPvTdjbX8fw5wDliM8a/4J+qGNlbxz7hzXSf5n4Hf7jsTTmTMl/QGqtfwRRElqO2zihEpMaLwU/r9p36G9gOu41emIAsXX7jsrEwCHySm500k60nj6V0=
  bucket: io.github.robertknight
  skip_cleanup: true
  local-dir: pkg
  upload-dir: passcards/builds/latest
  on:
    branch: master
  acl: public_read
- provider: s3
  access_key_id: AKIAJLAC2I2QPV6E33GA
  secret_access_key:
    secure: YyxwCqc8aPvsX432y3YhnRye2c/hyYylu6EBSGxgDG0Jg7IXtHKkcslGPvTdjbX8fw5wDliM8a/4J+qGNlbxz7hzXSf5n4Hf7jsTTmTMl/QGqtfwRRElqO2zihEpMaLwU/r9p36G9gOu41emIAsXX7jsrEwCHySm500k60nj6V0=
  bucket: io.github.robertknight
  skip_cleanup: true
  local-dir: webui
  upload-dir: passcards/web/latest
  on:
    branch: master
  acl: public_read
env:
  global:
  - CHROME_EXT_CLIENT_ID=663008561130-bgbo9tvbnr7j1ufrfuf52r4k3g8t9j9n.apps.googleusercontent.com
  - CHROME_EXT_APP_ID=olcdnhbhbfgncnocdfojpdjbododkimk
  # CHROME_EXT_REFRESH_TOKEN
  - secure: QgqHYQ8eg9sJLJcELRuC47B7R56/t8Y7fxi+dToZGeD82UHfJX2lZcKfn9coAVxRc8VvYSdOw0PCHxzeq61xCXRK/Rw4H/zrbyEyqwIPu6t82vyTP8S0/2qQa43suUPPL9vCw7/uohzeUd7MuZeAUofQdJPxCYF8RvNK7uBOYfk=
  # CHROME_EXT_CLIENT_SECRET
  - secure: NyDSq2y6xkHzFTTnoZuLrLfIdEmSzNTEQX9vQQCNyGfCWDbN4AYQd2whYAYV0IUaKdOh5/p+ixYvIaodjVol5ixRZ0p1R3IiqRfwV7YPum10goPiAb9e8D+tNgryz0SUMBNtJBT07yc3NsrTZAAsZfEb0ME4Emdp7O9C8q4d9pk=
  # NPM_AUTH_TOKEN
  - secure: "mZc/QM0FmeGwCPrUHsInrXp9gBXkyezEcioM0fyjmajboqerjfjz4uzn0C4iGEYXL5SBEbEuTcFfnaa3Mtuy6ftWrj5l0VbcimHgiwy20+FFeM5cJE4eC6uwnY6BNVECF0KwHM8qIMwY1w94mIVQCg8+P7rzE74xnUVl45k7BEE="
