language: node_js
notifications:
  email: false
node_js:
- '0.10'
before_script:
- export PATH=$PWD/node_modules/.bin:$PATH
after_success:
- make update-manifest-versions
- make firefox-addon
- make publish-chrome-extension
before_deploy:
- make test-package
deploy:
- provider: npm
  email: robertknight@gmail.com
  api_key:
    secure: RhRzH7umr4QyFjScdoR1nsWn/BHjQGrqwpFiavQzMgd1cEEnuWtTju8puGFct8++SJXH3bfcLp9kqtg3S2BB2qQM8ZqHlU1WGh8rKvgaFtmZCMdITPWqGmL/AuKQi+JL272jnReqwxi/leTNI1OQXL3TJXRv33JHDJphKJ+vGtE=
  skip_cleanup: true
- provider: s3
  access_key_id: AKIAJLAC2I2QPV6E33GA
  secret_access_key:
    secure: YyxwCqc8aPvsX432y3YhnRye2c/hyYylu6EBSGxgDG0Jg7IXtHKkcslGPvTdjbX8fw5wDliM8a/4J+qGNlbxz7hzXSf5n4Hf7jsTTmTMl/QGqtfwRRElqO2zihEpMaLwU/r9p36G9gOu41emIAsXX7jsrEwCHySm500k60nj6V0=
  bucket: io.github.robertknight
  skip_cleanup: true
  local-dir: pkg
  upload-dir: passcards/builds/latest
  on:
    branch: master
  acl: public_read
- provider: s3
  access_key_id: AKIAJLAC2I2QPV6E33GA
  secret_access_key:
    secure: YyxwCqc8aPvsX432y3YhnRye2c/hyYylu6EBSGxgDG0Jg7IXtHKkcslGPvTdjbX8fw5wDliM8a/4J+qGNlbxz7hzXSf5n4Hf7jsTTmTMl/QGqtfwRRElqO2zihEpMaLwU/r9p36G9gOu41emIAsXX7jsrEwCHySm500k60nj6V0=
  bucket: io.github.robertknight
  skip_cleanup: true
  local-dir: webui
  upload-dir: passcards/web/latest
  on:
    branch: master
  acl: public_read
env:
  global:
  - CHROME_EXT_CLIENT_ID=663008561130-bgbo9tvbnr7j1ufrfuf52r4k3g8t9j9n.apps.googleusercontent.com
  - CHROME_EXT_APP_ID=olcdnhbhbfgncnocdfojpdjbododkimk
  # CHROME_EXT_REFRESH_TOKEN
  - secure: QgqHYQ8eg9sJLJcELRuC47B7R56/t8Y7fxi+dToZGeD82UHfJX2lZcKfn9coAVxRc8VvYSdOw0PCHxzeq61xCXRK/Rw4H/zrbyEyqwIPu6t82vyTP8S0/2qQa43suUPPL9vCw7/uohzeUd7MuZeAUofQdJPxCYF8RvNK7uBOYfk=
  # CHROME_EXT_CLIENT_SECRET
  - secure: NyDSq2y6xkHzFTTnoZuLrLfIdEmSzNTEQX9vQQCNyGfCWDbN4AYQd2whYAYV0IUaKdOh5/p+ixYvIaodjVol5ixRZ0p1R3IiqRfwV7YPum10goPiAb9e8D+tNgryz0SUMBNtJBT07yc3NsrTZAAsZfEb0ME4Emdp7O9C8q4d9pk=
